import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// Import translations
import en from './locales/en.json';
import es from './locales/es.json';
import ja from './locales/ja.json';
import fr from './locales/fr.json';
import de from './locales/de.json';
import zh from './locales/zh.json';
import ko from './locales/ko.json';
import it from './locales/it.json';
import hi from './locales/hi.json';

// For other languages, they will be loaded dynamically or bundled if small
// Since we are using Lingo CLI, they will exist in the filesystem after 'lingo run'

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        resources: {
            en: { translation: en },
            // Placeholder for other languages to be generated by Lingo
            es: { translation: es },
            ja: { translation: ja },
            fr: { translation: fr },
            de: { translation: de },
            zh: { translation: zh },
            ko: { translation: ko },
            it: { translation: it },
            hi: { translation: hi },
        },
        fallbackLng: 'en',
        interpolation: {
            escapeValue: false,
        },
        detection: {
            order: ['localStorage', 'navigator'],
            caches: ['localStorage'],
        },
    });

export default i18n;
